### ISSUE TITLE
URL address bar flickering between pages?

### ISSUE THREAD

**Issue by KingScooty** [falsandtru/jquery-pjax#12] opened 2015-01-17 21:58 UTC
Is this flickering in the address bar normal when changing between pages? It's rather distracting.
I've recorded a video of it here:

http://wildfla.me/2q183W0i1M0N

**Comment by falsandtru** [comment] 2015-01-17 23:19
Thanks for reporting.
I will investigate. Please tell me how to reproduce and the environment such as a OS, browser.

The flicker to occur even my GitHub Pages?
Probably normally should not occur. Please tell me the occurrence conditions.

**Comment by KingScooty** [comment] 2015-01-18 10:19
Chrome 39
OSX Yosemite 

Here's a clip of the behaviour on your GitHub Pages:
http://wildfla.me/2N3r0y2G1i2S

**Comment by falsandtru** [comment] 2015-01-18 12:46
Thanks! Perhaps this process is the cause. Corresponding you.
https://github.com/falsandtru/jquery-pjax/blob/v2.34.2/src/ts/model/app.page.parser.ts#L36

**Comment by falsandtru** [comment] 2015-01-19 16:19
Fixed on my GitHub Pages without demo. Please check.

**Comment by KingScooty** [comment] 2015-01-19 18:49
It still seems to be happening.

http://wildfla.me/1i3m2M0o3X2t

**Comment by falsandtru** [comment] 2015-01-19 21:08
Sorry, it looks like my English was not good.
Modification is not yet applied to the demo page. Please look at the document page other than the demo page.

E.g.
Fixed
http://falsandtru.github.io/jquery-pjax/ -> http://falsandtru.github.io/jquery-pjax/api/
Not fixed
http://falsandtru.github.io/jquery-pjax/demo/falsandtru/ -> *

**Comment by KingScooty** [comment] 2015-01-19 21:13
Sorry! My fault!

Yes, http://falsandtru.github.io/jquery-pjax/ -> http://falsandtru.github.io/jquery-pjax/api/ works!

Confirmation:
http://wildfla.me/210Z090y1G2i

**Comment by falsandtru** [comment] 2015-01-19 21:33
Thanks for checking!
I will create a modified version from now. Please be also tell if you have any problem.

**Closed by falsandtru** 2015-01-19 21:33 UTC
Labels: bug
